apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: php-port
      protocol: TCP
      port: 5000
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 172.17.0.4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  selector:
    matchLable:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: php-port
        livenessPort: 80
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep telegraf && pgrep php'
          initialDelaySeconds: 15
          periodSeconds: 5