apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: wordpress
  ports:
    - port: 5050
      name: wp-port
      protocol: TCP
      targetPort: 5050
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress_image
          imagePullPolicy: Never
          ports:
          - containerPort: 5050
            name: wp-port
